# Generated by Django 3.0.4 on 2020-03-23 19:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlayer',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist', models.TextField()),
                ('title', models.TextField()),
                ('song', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('profile_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('multi_media', models.TextField()),
                ('tags', models.TextField()),
                ('comments', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('friends', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('posts', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('story', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('audio_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('customization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attr_id', models.IntegerField()),
                ('customization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('multi_media', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('profile_id', models.IntegerField()),
            ],
        ),
    ]
