# Generated by Django 3.0.5 on 2020-04-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibecheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_url',
            field=models.TextField(default='/static/vibecheck/img/default-avatar.png'),
        ),
    ]
