# Generated by Django 3.0.3 on 2020-03-04 17:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibecheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioPlayer',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist', models.TextField()),
                ('title', models.TextField()),
                ('song', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('profile_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=100)),
                ('text_content', models.TextField()),
                ('content', models.TextField()),
                ('tags', models.TextField()),
                ('comments', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.IntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=50)),
                ('friends', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('posts', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('story', models.CharField(max_length=100, validators=[django.core.validators.int_list_validator])),
                ('audio_player', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileCustomization',
            fields=[
                ('customization_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attr_id', models.IntegerField()),
                ('customization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
