# Generated by Django 3.0.5 on 2020-05-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibecheck', '0002_auto_20200430_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='colors',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
