# Generated by Django 3.0.4 on 2020-03-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibecheck', '0003_auto_20200323_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
