# Generated by Django 3.0.4 on 2020-03-24 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vibecheck', '0005_auto_20200323_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='profile_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibecheck.Profile'),
        ),
    ]
